apiVersion: v1 
kind: Service
metadata:
  name: angular-frontend-service
  labels:
    name: angular-frontend-service
    app: capitec-user-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    name: angular-frontend-app-pod
    app: capitec-user-service 
      