apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 4  
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: thapeloseema/capitec-user-service:frontend-windows-latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: database-service
        - name: DB_PORT
          value: "5432"  