apiVersion: v1 
kind: Service
metadata:
  name: spring-boot-backend-deploy
  labels:
    name: spring-boot-backend-deploy
    app: capitec-user-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    name: spring-boot-backendt-app-pod
    app: capitec-user-service
      